const data = {
    products: [
        {
            _id: '1',
            name:'Medium Balloon Gift',
            category:'Balloon Gifts',
            image: 'images/product-3.png',
            price:'120',
            countInStock: 10,
            brand: 'balloon',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
       {
            _id: '2',
            name:'Damola Balloon Gift',
            category:'Damola Gifts',
            image: 'images/product-3.png',
            price:'300',
            countInStock: 0,
            brand: 'balloon',
            rating: 5.0,
            numReviews: 50,
            description:'high quality product',
        },
        {
            _id: '3',
            name:'Oye Balloon Gift',
            category:'Oye Gifts',
            image: 'images/product-4.png',
            price:'300',
            countInStock: 20,
            brand: 'balloon',
            rating: 5.0,
            numReviews: 50,
            description:'high quality product',
        },
        {
            _id: '4',
            name:'Small Balloon Gift',
            category:'Birthday Gifts',
            image: 'images/product-2.png',
            countInStock: 30,
            price:'80',
            brand: 'balloon',
            rating:3.5,
            numReviews: 12,
            description:'high quality product',
        },
        {
            _id: '5',
            name:'Damola Balloon Gift',
            category:'Damola Gifts',
            image: 'images/product-3.png',
            price:'300',
            countInStock: 40,
            brand: 'balloon',
            rating: 5.0,
            numReviews: 50,
            description:'high quality product',
        },
        {
            _id: '6',
            name:'Oye Balloon Gift',
            category:'Oye Gifts',
            image: 'images/product-4.png',
            price:'300',
            countInStock: 10,
            brand: 'balloon',
            rating: 5.0,
            numReviews: 50,
            description:'high quality product',
        },
        {
            _id: '7',
            name:'Small Balloon Gift',
            category:'Birthday Gifts',
            image: 'images/product-2.png',
            price:'80',
            countInStock: 0,
            brand: 'balloon',
            rating: 4.3,
            numReviews: 12,
            description:'high quality product',
        },
    ],
};

export default data;